==== Anguilla LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact

| Anguilla | *Cable and Wireless (Anguilla) Ltd.* +
PO Box 77 +
THE VALLEY | *89 1 010* | Lawrence Stott +
PO Box 77 +
THE VALLEY +
Tel: +1 264 497 3100 +
Fax: +1 264 497 2501 +
E-mail: lawrence.stott@cwc.com
|===


==== Tonga LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact

| Tonga | *Tonga Communications Corporation Ltd. (TCC)* +
 Private Bag 4 +
 NUKU'ALOFA
| *89 676 01* | Timote F. Katoanga +
Fongoloa +
NUKU'ALOFA +
Tel: +676 20006 +
Fax: +676 26701 +
E-mail: info@kalianet.to
|===


==== United Kingdom LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact

| United Kingdom | *epay Limited* +
Ground Floor Kingfisher House, 2 Woodbrook Crescent +
BILLERICAY, CM12 0EQ | *89 44 90* | Jonathan Fricker +
Ground Floor Kingfisher House, 2 Woodbrook Crescent, +
BILLERICAY, CM12 0EQ +
Tel: +44 126 824 2222 +
E-mail: jfricker@epayworldwide.com
|===
