==== Brazil LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact
| Brazil | *Telefônica Brasil S/A* +
Avenida Eng. Luís Carlos Berrini, nº1.376 +
SÃO PAULO – SP | *89 55 23* | Katia Regina Do Nascimento Moreira +
Avenida Eng. Luís Carlos Berrini, nº1.376, 23º Andar +
SÃO PAULO – SP +
Tel: +55 11 98543 3511 +
E-mail: katia.moreira@telefonica.com
|===


==== Chad LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact
| Chad | *Airtel Tchad S.A* +
Avenue Charles de GaulleImmeuble Pierre Brock +
B.P : 5665, N'DJAMENA | *89 235 01* | Djibril TobeAvenue Charles de GaulleImmeuble Pierre Brock +
B.P : 5665, N'DJAMENA +
Tél : +235 22 52 31 77 +
E-mail: djibril.tobe@td.airtel.com
|===


==== Czech Rep. LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact
| Czech Rep. | *Nordic Telecom s.r.o.* +
Českomoravská 2408/1a +
190 00 PRAHA 9 | *89 420 04* | Martin Jahoda +
Českomoravská 2408/1a +
190 00 PRAHA 9 +
Czech Republic +
Tel.: +420 775 619 749 +
E-mail: martin.jahoda@nordictelecom.cz
|===


==== Palau ADD*

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact h| Effective date of usage
| Palau | *Palau National Communications Corporation* +
One Airport Rd +
P.O. Box 99KOROR, PW 96940 | *89 680 01* a| Myers Techitong +
One Airport Rd +
P.O. Box 99 +
KOROR, PW 96940 +
Tel: +680 587 9000 +
Fax: +680 587 1888 +
E-mail: tmyers@pnccpalau.com
| 14.II.2019

|===


==== Zambia LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact
| Zambia | *Zambia Telecommunications Company Ltd (ZAMTEL)* +
Zamtel House Corner of Church/Chilubi Roads +
PO Box 37000 +
LUSAKA | *89 260 03* | Cassandra Chakanika +
PO Box 37000 +
LUSAKA +
Zambia +
Tel: +260 950 003 605 +
E-mail: cassandra.chakanika@zamtel.co.zm

|===
