code: P.1203.1
title:
  en: Parametric bitstream-based quality assessment of progressive download and adaptive
    audiovisual streaming services over reliable transport – Video quality estimation
    module
