code: Q.3308.1
title:
  en: 'Resource control protocol No. 8 - Protocol at the interface between a policy
    decision physical entity and a customer premises network gateway policy enforcement
    physical entity (Rh interface): COPS alternative'
