code: J.343.6
title:
  en: Hybrid-FR objective perceptual video quality measurement for HDTV and multimedia
    IP-based video services in the presence of a full reference signal and non-encrypted
    bitstream data
id: J.343.6
