code: Q.4002.3 v.1
title:
  en: 'Originating identification presentation and originating identification restriction
    using IP multimedia core network subsystem; Conformance testing – Part 3: User
    side; Test suite structure and test purposes'
id: Q.4002.3 v.1
