==== Brazil LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact
| Brazil | Sercomtel Celular S/A +
Rua Prof. Joao Candido 555 +
Centro Londrina – PR | *89 55 15* | Alessandro Cianca +
Rua Prof. Joao Candido 555 +
Centro Londrina – PR +
Fax: +55 43 3324 3333 +
E-mail: alessandro.cianca@sercomtel.net.br

|===

==== Cyprus ADD

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact h| Effective date of usage
| Cyprus | *Cyprus Telecommunications Authority (CYTA)* +
1 Telelcommunications Street +
P.O. Box 24929 +
1396 NICOSIA | *89 357 02* | Andreas Theodorou +
1 Telelcommunications Street +
P.O. Box 24929 +
1396 NICOSIA +
Tel: +357 22701690 +
Fax: +357 22701766 +
E-mail: andreas.theodorou@cyta.com.cy | 30.IV.2019

|===

==== Czech Rep. LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact

| Czech Rep. | *Vodafone Czech Republic a.s.* +
náměstí Junkových 2 +
CZ - 155 00 PRAHA 5 | *89 420 31* | Petr Piskula +
náměstí Junkových 2 +
CZ - 155 00 PRAHA 5 +
Tel: +420 777 123 315 +
E-mail: petr.piskula@vodafone.com

| Czech Rep. | *Správa Zeleznicni Dopravni Cesty, s.o.* +
Dlážděná 1003/7 +
110 00 PRAHA 1 – NOVÉ MĚSTO | *89 420 98* | Ondřej Borovský +
Dlážděná 1003/7 +
110 00 PRAHA 1 – Nové Město +
Tel: +420 972 244 356 +
E-mail: borovsky@szdc.cz

|===

==== Ireland LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact
| Ireland | *IDT Card Services Ireland Ltd* +
5-7 Westland Square +
DUBLIN 2 | *89 353 04* | Kerry Kent +
5-7 Westland Square +
DUBLIN 2 +
Tel: +353 1 653 4706 +
E-mail: kkent@idteurope.com

| Ireland | *Virgin Media* +
Eastpoint Business Park +
DUBLIN 3 | *89 353 15* | Adrienne Costello +
Eastpoint Business Park +
DUBLIN 3 +
Tel: +353 1 245 8058 +
Email: adrienne.costello@virginmedia.ie

|===

==== Moldova (Republic of) LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact

| Moldova (Republic of) | *JSC Orange Moldova* +
Alba Iulia Street 75 +
MD-2012 CHISINAU | *89 373 01* | Veaceslav Roman +
Alba Iulia Street 75 +
MD-2012 CHISINAU +
Tel: +373 22575301 +
Fax: +373 22575306 +
E-mail: veaceslav.roman@orange.md

| Moldova (Republic of) | *Moldcell S.A.* +
Belgrad Street 3 +
MD-2060 CHISINAU | *89 373 02* | Angela Calancea +
Belgrad Street 3 +
MD-2060 CHISINAU +
Tel: +373 22400226 +
Fax: +373 22206207 +
E-mail: moldcell@moldcell.md

|===

==== Singapore LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact
| Singapore | *Singapore Telecommunications Ltd (SingTel)* +
31 Exeter Road +
05-00 Comcentre +
SINGAPORE 239732 | *89 65 01* | Chong Chin Hong +
Singtel Mobile Singapore Pte Ltd +
31 Exeter Road +
05-00 Comcentre +
SINGAPORE 239732 +
Tel: +65 9651 6499 +
E-mail: chchong@singtel.com

| Singapore | *Singapore Telecommunications Ltd (SingTel)* +
31 Exeter Road +
05-00 Comcentre +
SINGAPORE 239732 | *89 65 02* | Chong Chin Hong +
Singtel Mobile Singapore Pte Ltd +
31 Exeter Road +
05-00 Comcentre +
SINGAPORE 239732 +
Tel: +65 9651 6499 +
E-mail: chchong@singtel.com

|===
