code: Q.1912.5 D
title:
  en: 'Interworking between session initiation protocol (SIP) and bearer independent
    call control protocol (BICC) or ISDN user part (ISUP): Test suite structure and
    test purposes (TSS) for profile C'
