code: Q.4006.2 v.1
title:
  en: 'Communication waiting service using IP multimedia core network subsystem; Conformance
    testing – Part 2: Network side; Test suite structure and test purposes'
id: Q.4006.2 v.1
