code: H.850.7
title:
  en: 'Conformance of ITU-T H.810 personal health system: Personal Health Devices
    interface Part 10G: Transcoding for Bluetooth Low Energy: Personal Health Gateway
    - Continuous glucose monitoring'
id: H.850.7
