code: P.565
title:
  en: Framework for creation and performance testing of machine learning based models
    for the assessment of transmission network impact on speech quality for mobile
    packet-switched voice services
id: P.565
