Provides a formalized representation of OB and associated ITU publications.

= Vocabulary

* ITU OB: ITU Operational Bulletin.

* Message: a piece of information disseminated via ITU OB.
  Maps to a section within an OB issue.
+
Usually a message is connected to an ITU recommendation.
+
A message may be an amendment, or otherwise be a notice of general kind.

* Amendment: an update to a previous ITU publication
  (such as an annex to a previous OB issue or some external publication).
+
Always specifies the target being amended and the _changeset_.
  
* Amendment target: references the original publication being amended.
+
Must specify _publication_ (specifying original publication).
+
Other parameters identify specific issue of the publication
and depend on publication type:
_position_on_ for Lists annexed to previous OB issues;
_issue_ and _location_ for List V.
    
* External publication: ITU publication not annexed to a previous OB issue,
  such as List V.

* List: a dataset maintained by ITU in connection with a certain Recommendation.

* List position: a snapshot of that dataset deemed as valid at given point in time.
+
From time to time (could be every few years), a new snapshot of a List is created.
+
This happens around planned publication date of next OB issue, and that issue
is then published with dataset snapshot (List position) annexed to it.
+
Subsequent OB issues may disseminate amendments to that dataset,
until a new snapshot is published.

= Message types

Each OB message specifies a type, and a set of fields specific to the type.

Different representations of OB will use appropriate preset formatting
for each message type, making use of those fields.

The most generic type is `custom`, which only requires `contents` key to refer to a file
that provides contents for the message (only AsciiDoc is supported for now).

* running_annexes
* approved_recommendations
* service_restrictions
* telephone_service
* custom
* publication_amendment
