id: >-
  LIST OF DATA NETWORK IDENTIFICATION CODES (DNIC) (ACCORDING TO ITU-T
  RECOMMENDATION X.121 (10/2000))
url: 'https://www.itu.int/pub/T-SP-OB.1318-2025'
recommendation: null
title:
  en: >-
    LIST OF DATA NETWORK IDENTIFICATION CODES (DNIC) (ACCORDING TO ITU-T
    RECOMMENDATION X.121 (10/2000))
