==== Jordan (country code +962)

===== Communication of 6.XII.2018:

The _Telecommunications Regulatory Commission (TRC),_ Amman,
announces the allocation of new number ranges as follows:

|===
h| Service h| Operator h| Number ranges h| Governorate h| Activation date

| Fixed / Geographic telecommunications | Al Bahrainia +
 Al Urdunia +
 Liltaknia Wa +
 Alitisalat | +962 6 222 XXXX | Amman | Immediate

|===

===== Contact:

Eng. Hala Kharbat +
Telecommunications Services and Networks Regulation Department +
Telecommunications Regulatory Commission (TRC) +
Shmeisani - Abdel Hamid Sharaf Street, +
Building No. 90 +
AMMAN 11194 +
Jordan +
Tel: +962 6 5501120 ext: 2330 +
Fax: +962 6 5690830 +
E-mail: hala.kharbat@trc.gov.jo

==== Mauritius (country code +230)

===== Communication of 7.XII.2018

The _Information and Communication Technologies Authority (ICTA),_ Port-Louis,
announces that number block +230 583X XXXX is allocated to the operator
"Cellplus Mobile Communications Ltd" for Mobile services since 1 January 2013.

All Administrations, recognized operating agencies and service providers
are kindly requested to ensure access to this number block.

===== Contact

Mr Nikhil JORAI +
Information and Communication Technologies Authority (ICTA) +
Level 12 The Celicourt +
6, Sir Celicourt Antelme Street +
PORT LOUIS +
Mauritius +
Tel: +230 217 2222 +
Fax : +230 217 7777 +
E-mail: icta@intnet.mu +
URL: www.icta.mu


==== Sao Tome and Principe (country code +239)

===== Communication of 11.XII.2018

The _Autoridade Geral de Regulação (AGER)_, São Tomé,
announces the following dialling procedures and Legal Time:

- Country Code: 239
- International Prefix: 00
- National Prefix: Not available
- Length of national (significant) number (excluding the national prefix): minimum 3 digits, maximum 7 digits
- Universal Time Coordinated/Summer Time: *UTC+00*

Remarks: Legal Time that is currently UTC+01, will be set from *1st January 2019* at 02:00H AM
to *UTC* according to the Government *Decree no. 34/2018* of 11^th^ December 2018.

===== Contact

Eng. Candido Frota +
President +
Autoridade Geral de Regulação (AGER) +
Avenida 12 de Julho N° 54 +
SÃO TOMÉ +
Sao Tome and Principe +
Tel: +239 2224995 +
Email: candidofrota1963@gmail.com
