==== Burkina Faso (country code +226)

===== Communication of 4.III.2019:

The _Autorité de Régulation des Communications Electroniques et des Postes (ARCEP)__,_ Ouagadougou_,_
announces the following update to the National Numbering Plan of Burkina Faso.

Assignment of the following new number series format from *07 00 MCDU* to *07 99 MCDU* to*ORANGE Burkina Faso* for mobile service:

|===
.2+h| +++<abbr title="national destination code">NDC</abbr>+++ +
or leading digits +
of +++<abbr title="national (significant) number">N(S)N</abbr>+++ 2+h| N(S)N number length .2+h| Usage of ITU-T E.164 number .2+h| Additional information .2+h| Time and date of introduction
h| Minimum h| Maximum

| 07 | 8 | 8 | Non-geographic number – Mobile telephone service | ORANGE Burkina Faso | 2019-03-01-00:00 UTC

|===

===== Contact

Autorité de Régulation des Communications Electroniques et des Postes (ARCEP) +
B.P. 6437 +
 OUAGADOUGOU 01 +
 Burkina Faso +
 Tel: +226 25 37 53 60/61/62 +
 Fax: +226 25 37 53 64 +
 E-mail: secretariat@arcep.bf +
 URL: www.arcep.bf


==== Kiribati (country code +686)

===== Communication of 15.III.2019:

The _Communications Commission of Kiribati (__CCK),_ Betio, Tarawa,
announces updates to the National Numbering Plan of Kiribati.

*Description of introduction of new resource +
 for national ITU-T E.164 numbering plan**for country code 686:*

|===
.2+h| +++<abbr title="national destination code">NDC</abbr>+++ +
or leading digits +
of +++<abbr title="national (significant) number">N(S)N</abbr>+++ 2+h| N(S)N number length .2+h| Usage of ITU-T E.164 number .2+h| Additional information .2+h| Time and date of introduction
h| Minimum h| Maximum

| 740 22 000 to740 29 999 | 8 | 8 | ATHKL SIP IPVPN 2+| 13/03/2019
| 740 81 000 to740 81 999 | 8 | 8 | ATHKL SIP IPVPN 2+| 13/03/2019

|===

The first range of numbers will expand the current existing number range allocations of (74020000-74021999) 2000 range to a 10000 range (74020000-74029999). So only an additional of another 8000 numbers is needed hence the first 2000 have already existed.

The second range of numbers is a new introduction of numbers to the ATHKL number allocations.

===== Contact

Mr Tiare Erekana +
 CEO +
 Communications Commission of Kiribati (CCK) +
Temakin +
 BETIO, TARAWA +
 Kiribati +
 Tel: +686 75125488 +
 E-mail: mailto:ceo@cck.ki[ceo@cck.ki] +
URL: www.cck.ki


==== Mauritius (country code +230)

===== Communication of 7.III.2019:

The _Information and Communication Technologies Authority (ICTA),_ Port-Louis,
announces that new non-geographic fixed-mobile converged numbers range
has been opened in the Republic of Mauritius by the following mobile operators
since 31 January 2019.

|===
h| Operator h| Usage of ITU-T E.164 number h| Dialling Format

| Emtel Ltd | Non-geographic fixed-mobile converged numbers a| +230 5430 XXXX +
 to +
 +230 5439 XXXX

|===

===== Contact

Mr J. Louis +
Information and Communication Technologies Authority (ICTA) +
Level 12 The Celicourt +
6, Sir Celicourt Antelme Street +
PORT LOUIS +
Mauritius +
Tel: +230 217 2222 +
Fax: +230 217 7777 +
E-mail: icta@intnet.mu +
URL: www.icta.mu +


