code: H.248.81
title:
  en: 'Gateway control protocol: Guidelines on the use of the international emergency
    preference scheme (IEPS) call indicator and priority indicator in ITU-T H.248
    profiles'
id: H.248.81
