code: Q.4007.1 v.1
title:
  en: 'Explicit communication transfer using IP multimedia core network subsystem;
    Conformance testing – Part 1: Network side and user side; Protocol implementation
    conformance statement'
id: Q.4007.1 v.1
