==== Lithuania

===== Communication of 18.IV.2019:

_Granting of Recognized Operating Agency (ROA) status_

The _Communications Regulatory Authority_, Vilnius, announces that the following telecommunication operators and service providers have been granted the status of Recognized Operating Agency (ROA), in accordance with Article 6 of, and Nos.1007 and 1008 of the Annex to, the Constitution of ITU.

[width=584]
|===
| _Company's (ROA) name and address_ | _Contact_

| Telia Lietuva, AB +
Vilnius, Lvovo g. 25 | Tel: +370 5264 1817 +
E-mail: info@telia.lt

| AB Lietuvos radijo ir televizijos centras +
Vilnius, Sausio 13-osios g. 10 | Tel.: +370 5204 03 00 +
Fax: +370 5204 03 25E-mail: info@telecentras.lt

| UAB "CSC TELECOM" +
Vilnius, Perkūnkiemio g. 7 | Tel.:+370 52101790 +
E-mail: info@csc.lt

| UAB "Digitela" +
Vilnius, Vytenio g. 6 | Tel.: +370 52104156 +
Fax: +370 52104155 +
E-mail: info@digitela.lt

| UAB "Bitė Lietuva" +
Vilnius, Žemaitės g. 15 | Tel.: +370 656 00656 +
Fax: +370 699 00111 +
E-mail: bendraukime@bite.lt

| UAB "Nacionalinis telekomunikacijų tinklas" +
Vilnius, Naugarduko g. 102 | Tel.: +370 5 205 6000 +
Fax: +370 700 00034 +
E-mail: info@ntt.lt

| Mediafon Carrier Services, UAB +
Vilnius, m. Olimpiečių g. 1-33 | Tel.: +370 5 239 0901 +
E-mail: info@mediafoncs.lt
| UAB "Penkių kontinentų komunikacijų centras" +
Vilnius, Kareivių g. 2 | Tel.: +370 5 266 4555 +
E-mail: info@penki.lt
| UAB "TELE2" +
Vilnius, Upės g. 23 | Tel.: +370 684 00 117 +
Fax: +370 5 236 6455E +
-mail: tele2.lt@tele2.com
| UAB "Teledema" +
Kauno m. Vytauto pr. 32 | Tel.: +370 657 82117 +
E-mail: info@teledema.lt
| UAB "ECOFON" +
Vilnius, Lvovo g. 89A-2 | Tel.: +370 5 255 5050 +
Fax: +370 5 255 5001 +
E-mail: office@ekofon.lt
| UAB "Teletel" +
Klaipėda, Debreceno g. 11-52 | Tel.: +370 68784263E-mail: info@teletel.lt
| UAB "EUROCOM" +
Vilnius, Žemaitės g. 15 | Tel.: +370 659 11 700 +
Fax: +370 5 274 4612 +
E-mail: eurocom@eurocom.lt

|===

For further information, please contact:

Communications Regulatory Authority +
Mortos Str. 14 +
03219 VILNIUS +
Lithuania +
Tel: +370 52105633 +
Fax: +370 52161564 +
E-mail: rrt@rrt.lt +
URL: www.rrt.lt +


