code: J.343.5
title:
  en: Hybrid-FRe objective perceptual video quality measurement for HDTV and multimedia
    IP-based video services in the presence of a full reference signal and encrypted
    bitstream data
