code: Q.4011.2 v.1
title:
  en: 'Closed user group using IP multimedia core network subsystem; Conformance test
    specification – Part 2: Test suite structure and test purposes; Network side'
id: Q.4011.2 v.1
