code: Q.4001.2 v.1
title:
  en: 'IMS specific use of session initiation protocol and session description protocol;
    Conformance testing – Part 2: Test suite structure and test purposes'
id: Q.4001.2 v.1
