code: Q.4002.1 v.1
title:
  en: 'Originating identification presentation and originating identification restriction
    using IP multimedia core network subsystem; Conformance testing – Part 1: Network
    side and user side; Protocol implementation conformance statement'
id: Q.4002.1 v.1
