code: H.850.4
title:
  en: 'Conformance of ITU-T H.810 personal health system: Personal Health Devices
    interface Part 10D: Transcoding for Bluetooth Low Energy: Personal Health Gateway
    - Glucose meter'
