code: Q.4012.1 v.1
title:
  en: 'Anonymous communication rejection and communication barring using IP multimedia
    core network subsystem; Conformance testing specification – Part 1: Protocol implementation
    conformance statement'
id: Q.4012.1 v.1
