code: Q.3228
title:
  en: Signalling requirements and protocol at the M1 interface between the transport
    location management physical entity and the mobile location management physical
    entity (P)
id: Q.3228
