code: Q.3314
title:
  en: Requirements and protocol at the interface between the mobile location management
    physical entity used as a proxy and the central instance of the mobile location
    management physical entity (M9 interface)
