code: Q.4012.2 v.1
title:
  en: 'Anonymous communication rejection and communication barring using IP multimedia
    core network subsystem; Conformance test specification – Part 2: Test suite structure
    and test purposes; Network side'
id: Q.4012.2 v.1
