==== Austria ADD

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact h| Effective date of usage
| Austria | *A1 Telekom Austria AG* +
Lassallestraße 9 +
A-1020 WIEN | *89 43 12* | Mag. Michael Seitlinger, LL.M. +
Lassallestraße 9 +
A-1020 WIEN +
Tel: +43 50 664 24560 +
E-mail: regulierung@a1.at | 1.IV.2005

|===

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact
| Austria | *Hutchison Drei Austria GmbH* +
Brünner Straße 52 +
A-1210 WIEN | *89 43 10* | Dr Natalie Ségur-Cabanac +
Brünner Straße 52 +
A-1210 WIEN +
Tel: +43 5066063202 +
E-mail: natalie.segur-cabanac@drei.com

|===


==== Hong Kong, China ADD

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact h| Effective date of usage

| Hong Kong, China | *CITIC TELECOM INTERNATIONAL LIMITED* +
25/F, CITIC Telecom Tower, +
93 Kwai Fuk Road +
Kwai Chung, Hong Kong
| *89 852 01* | Sutton Cheung +
25/F, CITIC Telecom Tower, +
93 Kwai Fuk Road +
Kwai Chung, Hong Kong +
Tel: +852 237788334 +
E-mail: suttoncheung@citictel.com | 1.XII.2018

|===


==== Japan ADD

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact h| Effective date of usage

| Japan | *Rakuten Mobile Network, Inc.* +
1-14-1, Tamagawa, +
 Setagaya-ku, TOKYO
| *89 81 09* | Shigehiro Miyashita +
1-14-1, Tamagawa, Setagaya-ku +
TOKYO +
Tel: +81 50 5817 1360 +
Fax: +81 3 6316 3420 +
E-mail: rmn-sousetsu@mail.rakuten.com | 30.IV.2019

| Japan | *Fujitsu Limited* +
4-1-1 Kamikodanaka, Nakahara-ku, +
KAWASAKI 211-8588 | *89 81 11* | Yoshinori Yuki +
Fujitsu LimitedShinKawasaki Technology Square, +
 1-1 Shin-ogura, Saiwai-ku +
 KAWASAKI 212-8510 +
 Tel: +81 44 280 9862 +
 E-mail: fj-wls-mx@dl.jp.fujitsu.com | 1.V.2019

|===


==== Malaysia ADD

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact h| Date of registration
| Malaysia | *webe digital sdn bhd* +
159 Jalan Templer +
46050 PETALING +
JAYA, SELANGOR | *89 60 153* | Muhamad Hafiz Bin Senin +
Regulatory Department, Level 8, +
 159 Jalan Templer +
 46050 PETALING +
 JAYA, SELANGOR +
 Tel: +60 11 1000 2000 +
 E-mail: muhamad.hafiz@webe.com.my | 5.X.2018

|===

==== Romania SUP

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact h| Date of cancellation

| Romania | *2K TELECOM S.R.L.* +
10 Mihai Bravu Blvd +
PLOIESTI | *89 40 15* | Alexandru Ghita +
Sos. Pipera-Tunari nr. 1/VI, Twin Towers +
 Corp 1, Et. 8, Voluntari +
 Jud. Ilfov, 077190 +
 Tel: +40 21 344 84 00 +
 Fax: +40 21 344 84 02 +
 E-mail: alex.ghita@2ktelecom.ro | 12.XI.2018

|===

==== Spain LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact

| Spain | *ORANGE ESPAGNE, S.A.U.* +
Paseo Club Deportivo - +
 P. E. La Finca 1 Edif. 5 +
 28223 Pozuelo de Alarcón +
 MADRID | *89 34 01* | Isabel Santaella García Royo +
Paseo Club Deportivo - P. E. La Finca 1 Edif. 5 +
28223 Pozuelo de Alarcón +
MADRID +
Tel: +34 911839702 +
Fax: +34 912521632 +
E-mail: isabel.santaella@orange.com; carmen.luque@orange.com

| Spain | *Euskaltel, SA* +
Parque Tecnológico 809 +
48160 DERIO-BIZKAIA | *89 34 02* | Euskaltel, SA +
Parque Tecnológico 809 +
48160 DERIO-BIZKAIA +
Tel: +34 94 401 1206 +
Fax: +34 94 401 1028 +
E-mail: juridico@euskaltel.com

| Spain | *Telefónica Móviles España, SAU* +
Distrito C, Edificio Sur 3, +
Planta 2 +
28050 MADRID | *89 34 03* | Alberto Moreno Rebollo +
Distrito C, Edificio Sur 3, +
Planta 2 +
28050 MADRID +
Tel: +34 914820767 +
Fax: +34 914820766 +
E-mail: alberto.morenorebollo@telefonica.com

| Spain | *Xfera Móviles, S.A.* +
Avenida de la Vega 15 +
28108 MADRID | *89 34 04* | Daniel Ruiz +
Avenida de la Vega 15 +
28108 MADRID +
Tel: +34 91 131 5505 +
Fax: +34 91 131 5684 +
E-mail: daniel.ruiz@masmovil.com

| Spain | *Telecor SA* +
c/ Hermosilla 112 +
28009 MADRID | *89 34 05* | D. José Eduardo Urquiza +
c/ Hermosilla 112 +
28009 MADRID +
Tel: +34 91 597 2876 +
Fax: +34 91 597 2876 +
E-mail: notificaciones@elcorteingles.es

| Spain | *R Cable y Telecomunicaciones Galicia, SA* +
CI Real 85 +
15003 CORUNA A | *89 34 06* | Sr D. Alfredo Ramos González +
Calle Real No. 85 +
A CORUÑA 15003 +
Tel: +34 9 8191 1020 +
Fax: +34 9 8191 1009 +
E-mail: rexistroentradar@mundo-r.net

| Spain | *Telefónica Móviles España, SAU* +
Distrito C, Edificio Sur 3, Planta 2 +
28050 MADRID | *89 34 07* | Alberto Moreno Rebollo +
Distrito C, Edificio Sur 3, Planta 2 +
28050 MADRID +
Tel: +34 680 072 009 +
Fax: +34 680 077 857 +
E-mail: alberto.morenorebollo@telefonica.com

| Spain | *Ruzorange sl* +
Avda Juan Carlos I - JC1 +
55 planta 16 +
30100 MURCIA | *89 34 09* | Sr. José Luis Garay Vicente +
Avda Juan Carlos I - JC1 +
55 planta 16 +
30100 MURCIA +
Tel: +34 652 005 881 +
Fax: +34 968 644 211E-mail:

| Spain | *PROCONO S.A.* +
Calle Alderete 22 +
29013, MALAGA | *89 34 12* | Antonio Carrillo Baeza +
Avenida de Cádiz, 58 +
14013 CÓRDOBA +
Tel: +34 662666970 +
Fax: +34 957760337 +
E-mail: josecarrillo@ptvtelecom.com

| Spain | *Vodafone ONO, SAU* +
Avenida de América 115 +
28042 MADRID | *89 34 18* | Luisa Belda Cuesta +
Avenida de América 115 +
28042 MADRID +
Tel: +34 91 180 9473 +
Fax: +34 91 180 9321 +
E-mail: regulacionycompetencia@corp.vodafone.es

| Spain | *ORANGE ESPAGNE, S.A.U.* +
Paseo Club Deportivo - +
P. E. La Finca 1 Edif. 5 +
28223 Pozuelo de Alarcón +
MADRID | *89 34 21* | Isabel Santaella García Royo +
Paseo Club Deportivo - P. E. La Finca 1 Edif. 5 +
28223 Pozuelo de Alarcón +
MADRID +
Tel: +34 911839702 +
Fax: +34 912521632 +
E-mail: isabel.santaella@orange.com; carmen.luque@orange.com

| Spain | *R Cable y Telecomunicaciones Galicia, SA* +
CI Real 85 +
15003 CORUNA A | *89 34 25* | Sr D. Alfredo Ramos González +
Calle Real No. 85 +
A CORUÑA 15003 +
Tel: +34 9 8191 1020 +
Fax: +34 9 8191 1009 +
E-mail: rexistroentradar@mundo-r.net

| Spain | *IBERFIBRA GESTIÓN DE REDES DE BANDA ANCHA, S.A* +
Glorieta de Cuatro +
Caminos 6/7. Planta 5 +
Centro +
28020 MADRID | *89 34 29* | Enrique Chao Lumbreras +
Glorieta de Cuatro +
Caminos 6/7. Planta 5 +
Centro +
28020 MADRID +
Tel: +34 911 440 160 +
Fax: +34 911 440 203 +
E-mail: echao@iberfibra.com

| Spain | *Telefónica de España S.A.* +
Gran Vía 28 +
28013 MADRID | *89 34 34* | Alberto Moreno Rebollo +
Distrito C, Edificio Sur 3, Planta 2 +
28050 MADRID +
Tel: +34 91 584 1808 +
Fax: +34 91 319 6087 +
E-mail: alberto.morenorebollo@telefonica.com

| Spain | *Vodafone España S.A.* +
Avenida de América 115 +
28042 MADRID | *89 34 56* | Luisa Belda Cuesta +
Avenida de América 115 +
28042 MADRID +
Tel: +34 91 587 6385 +
Fax: +34 91 587 6381 +
E-mail: regulacionycompetencia@corp.vodafone.es

| Spain | *Vodafone Enabler España, S.L.* +
Avenida de América 115 +
28042 MADRID | *89 34 57* | Luisa Belda Cuesta +
Avenida de América 115 +
28042 MADRID +
Tel: +34 918 253 333 +
E-mail: regulacionycompetencia@corp.vodafone.es

|===

==== Turkey LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact

| Turkey | *Turkcell İletişim Hizmetleri AŞ* +
Aydınevler Mahallesi İnönü +
Caddesi No:20 +
Maltepe ISTANBUL | *89 90 01* | Semi Enis Morkoyun +
Aydınevler Mahallesi İnönü +
Caddesi No:20 +
Maltepe ISTANBUL +
Tel: +90 532 210 48 45 +
E-mail: semi.morkoyun@turkcell.com.tr

| Turkey | *Vodafone Telekomünikasyon AŞ* +
Büyükdere Caddesi No:251 +
34398 Maslak Şişli ISTANBUL | *89 90 02* | Atila Voyvat +
Büyükdere Caddesi No:251 +
34398 Maslak Şişli ISTANBUL +
Tel: +90 542 705 00 00 +
E-mail: atila.voyvat@vodafone.com

|===
