code: Q.3943.1
title:
  en: 'Conformance tests specification for the originating identification presentation
    and originating identification restriction using the IP multimedia core network
    subsystem – Part 1: Protocol'
