code: Q.4005.1 v.1
title:
  en: 'Conference service using IP multimedia core network subsystem; Conformance
    testing – Part 1: Network side and user side; Protocol implementation conformance
    statement'
id: Q.4005.1 v.1
