code: Q.731.5
title:
  en: 'Stage 3 description for number identification supplementary services using
    Signalling System No. 7 : Stage 3 description for number identification supplementary
    services using Signalling System No.7 – Connected line identification presentation'
id: Q.731.5
