==== Faroe Islands LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact
| Faroe Islands | *P/F Hey* +
Smyrilsvegur 5, PO Box 109 +
FO-110 TORSHAVN | *89 298 02* | Erland Simonsen +
Smyrilsvegur 5, PO Box 109 +
FO-110 TORSHAVN +
Tel: +298 202020 +
Fax: +298 202021 +
E-mail: hey@hey.fo
|===

==== Japan ADD

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact h| Effective date of usage
| Japan | *NTT Communications Corporation* +
2-3-1 Otemachi, Chiyoda-ku +
TOKYO 100-8019 | *89 81 12* | Hiroshi Ootsubo +
2-3-1 Otemachi, Chiyoda-ku +
TOKYO 100-8019 +
Tel: +81 3 6700 8320 +
Fax: +81 3 5202 5043 +
E-mail: mt-ns@ntt.com | 26.IV.2019
|===


==== Samoa LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact
| Samoa | *Office of the Regulator* +
Private Bag +
APIA | *89 685 02* | Lefaoali'i Unutoa Auelua-Fonoti +
Regulator +
Private Bag +
Mulinuu +
APIA +
Tel: +685 30282 +
Fax: +685 30281 +
E-mail: SpecTech@regulator.gov.ws
|===


==== Sweden ADD

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact h| Effective date of usage
| Sweden | *Fink Telecom Services* +
Paradieshofstrasse 101 +
4054 BASEL +
(Switzerland) | *89 46 12* | Andreas Fink +
Paradieshofstrasse 101 +
4054 BASEL +
(Switzerland) +
Tel: +41 78 6677333 +
E-mail: afink@fink-telecom.com | 8.III.2019
|===


==== Sweden SUP

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact h| Date of cancellation
| Sweden | *Abbla Mobile S.A.* +
c/Saturno, +
1 Pozuelo de Alarcón +
E-28224 MADRID +
(Spain)
| *89 46 06* | Detlef Stubec/Saturno, +
1 Poluezo de Alarcón +
E-28224 MADRID +
(Spain) +
Tel: +34 678 52 6699 +
Fax: +34 913 51 8074 +
E-mail: dstuebe@abbla.com
| 22.I.2008
|===


==== Viet Nam LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact
| Viet Nam | *MOBIFONE CORPORATION (MOBIFONE)* +
MobiFone Building, Lot VP1, +
Yen Hoa Ward, Cau Giay District, Hanoi
| *89 84 01* | Nguyen Duy Binh +
MobiFone Building, Lot VP1, +
Yen Hoa Ward, Cau Giay District, Hanoi +
Tel: +84 24 37831766 +
Fax: +84 24 37831767 +
Email: binh.nguyen@mobifone.vn
| Viet Nam | *VIETNAM POSTS AND TELECOMMUNICATIONS GROUP (VNPT)* +
57 Huynh Thuc Khang, Hanoi | *89 84 02* | Dao Viet Chien +
57 Huynh Thuc Khang, Hanoi +
Tel: +84 24 37741215 +
Fax: +84 24 37741205 +
Email: chiendv@vnpt.vn
|===
