==== Eritrea LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact

| Eritrea | *Eritrea Telecommunication Services Corporation (EriTel)* +
11 Semaetat Street +
ASMARA | *89 291 01* | Tesfaselassie Berhane +
11 Semaetat Street +
ASMARA +
Tel: +291 1124655 +
Fax: +291 1120938 +
E-mail: eritel@tse.com.er

|===

==== Fiji LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact

| Fiji | *Vodafone Fiji Pte Limited* +
Private Bag +
SUVA | *89 679 01* | Andrew Kumar +
c/- Vodafone Fiji Pte Limited +
168 Princes Road +
SUVA +
Tel: +679 331 2000 +
Fax: +679 331 2007 +
E-mail: andrew.kumar@vodafone.com.fj

| Fiji | *Digicel (Fiji) Pte Limited* +
Level 3, Digicel House +
5 Vuna RdNABUA | *89 679 02* | Peter Rigamoto +
Digicel (Fiji) Pte Limited +
PO Box 13811 +
SUVA +
Tel.: +679 7017 480 +
Email : peter.rigamoto@digicelgroup.com

|===


==== Israel LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact

| Israel | *Cellcom Israel Ltd* +
10 Hagavish Street +
P.O. Box 4060 +
NETANYA 42140 | *89 972 02* | Nir Yogev +
10 Hagavish Street +
P.O. Box 4060 +
NETANYA 42140 +
Tel: +972 52 9989540 +
Fax: +
E-mail: niryo@cellcom.co.il

| Israel | *Cellcom Israel Ltd* +
10 Hagavish Street +
P.O. Box 4060 +
NETANYA 42140 | *89 972 03* | Nir Yogev +
10 Hagavish Street +
P.O. Box 4060 +
NETANYA 42140 +
Tel: +972 52 9989540 +
Fax: +
E-mail: niryo@cellcom.co.il

| Israel | *Golan Telecom Ltd* +
98 Yigal Allon +
67 891 TEL AVIV | *89 972 08* | Oren Most +
98 Yigal Allon +
67 891 TEL AVIV +
Tel: +972 58 4499499 +
Fax: +
E-mail: omost@golantelecom.co.il

| Israel | *Pelephone Communications Ltd* +
33 Yitzhak Rabin Road +
GIVATAIM 61620 | *89 972 50* | Ido Rosenberg +
33 Yitzhak Rabin Road +
GIVATAIM 61620 +
Tel: +972 50 7078912 +
Fax: +
E-mail: ido@pelephone.co.il

|===

==== Italy LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact

| Italy | *Telecom Italia S.p.A.* +
Via Gaetano Negri 1 +
 20123 MILANO
| *89 39 01* | Dr Donatella ChiaraTelecom Italia S.p.A., +
 Via Guglielmo Reiss Romoli, 274I-10148 TORINO +
 Tel: +39 011 228 6956 +
 Fax: +39 011 228 5520 +
 E-mail: donatella.chiara@telecomitalia.it

| Italy | *Vodafone Omnitel S.p.A.* +
Via Jervis 13 +
IVREA (TO) | *89 39 10* | Vodafone Omnitel S.p.A. +
Via Jervis 13 +
IVREA (TO) +
Tel: +39 06 5092 2512 +
Fax: +39 06 5006 5808 +
E-mail: vodafoneomnitel@pocert.vodafone.it

|===


==== Italy SUP

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact h| Date of cancellation

| Italy | *IPSE 2000* +
Piazza del Caprettari 70 +
I-00186 ROMA | *89 39 77* | Filippo Dallatorre +
V. delle Testuggini, s.n.c. +
I-00134 ROMA +
Tel: +39 06 5799 5703 +
Fax: +39 06 5799 5820 +
E-mail: | 31.XII.2007

| Italy | *Blu S.p.A.* +
Vía Cintia, Svincolo +
Fuorigrotta +
I-80126 NAPOLI | *89 39 98* | A. Tagliaferro +
Via A. Nibby 10 +
I-00161 ROMA +
Tel: +39 06 8521 6207 +
Fax: +39 06 8521 6290 +
E-mail: | 2.X.2002

|===


==== Palau SUP

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact h| Date of cancellation
| Palau | *Palau Mobile Corporation* +
P.O. Box 8084 +
KOROR STATE, +
Palau PW96940 | *89 680 80* | Mark Yu Cheng Lin +
P.O. Box 8084 +
KOROR STATE, Palau PW96940 +
Tel: +680 488 1903 +
Fax: +680 488 0607 +
E-mail:marklin@viamedia.com.tw | 30.IX.2018

|===

==== Switzerland LIR

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact

| Switzerland | *Swisscom* +
Alte Tiefenaustrasse 6 +
CH-3050 BERN | *89 41 00* | Wylenmann Regula +
Alte Tiefenaustrasse 6 +
CH-3050 BERN +
Tel.: +41 58 223 47 82 +
E-mail: regula.wylenmann@swisscom.com

| Switzerland | *Swisscom* +
Alte Tiefenaustrasse 6 +
CH-3050 BERN | *89 41 01* | Wylenmann Regula +
Alte Tiefenaustrasse 6 +
CH-3050 BERN +
Tel.: +41 58 223 47 82 +
E-mail: regula.wylenmann@swisscom.com

| Switzerland | *Sunrise Communications AG* +
Binzmühlestrasse 130 +
CH-8050 Zürich | *89 41 02* | Meier Andreas +
Binzmühlestrasse 130 +
CH-8050 Zürich +
Tel.: +41 58 777 77 77 +
Fax: +41 58 777 69 99 +
E-mail: andreas.meier@sunrise.net

| Switzerland | *Salt Mobile SA* +
Regulatory Affairs +
Rue du Caudray 4 +
CH-1020 Renens | *89 41 03* | Beghi Luca +
Rue du Caudray 4 +
CH-1020 Renens +
Tel.: +41 21 216 1010 +
Fax: +41 21 216 1515 +
E-mail: luca.beghi@salt.ch

| Switzerland | *relario AG* +
Lindenstrasse 16 +
CH-6340 Baar | *89 41 04* | Klebor Stefan +
Lindenstrasse 16 +
CH-6340 Baar +
Tel.: +41 61 666 63 30 +
Fax: +41 61 666 63 31 +
E-mail: sk@relario.com

| Switzerland | *Die Schweizerische Post AG Information Technology Services* +
Webergutstrasse 12 +
CH-3030 Bern (Zollikofen) | *89 41 23* | Weber Marco +
Webergutstrasse 12 +
CH-3030 Bern (Zollikofen) +
Tel.: +41 31 338 0953 +
Fax: +41 31 338 6654 +
E-mail: webermarc@post.ch

| Switzerland | *Lycatel GmbH* +
Hermetschloostrasse 73 +
CH-8048 Zürich | *89 41 24* | Thakur Suzie +
Hermetschloostrasse 73 +
CH-8048 Zürich +
Tel.: +41 44 240 38 38 +
Fax: +41 44 240 39 39 +
E-mail: info@lycatel.ch

| Switzerland | *UPC Schweiz GmbH* +
Richtiplatz 5 +
CH-8304 Wallisellen | *89 41 25* | Reichmuth Benjamin +
Richtiplatz 5 +
CH-8304 Wallisellen +
Tel.: +41 58 388 98 96 +
Fax: +41 58 388 98 96 +
E-mail: benjamin.reichmuth@upc.ch

| Switzerland | *WeMobile SA* +
Rue de Veyrot 14 +
CH-1217 Meyrin | *89 41 26* | Ben Amer Walid +
Rue de Veyrot 14 +
CH-1217 Meyrin +
Tel.: +41 22 777 7122 +
Fax: +41 22 777 7122 +
E-mail: walid@wemobile.ch

| Switzerland | *Beeone Communications SA* +
route des Jeunes 6 +
CH-1227 Carouge GE | *89 41 29* | Schreier Olivier +
route des Jeunes 6 +
CH-1227 Carouge GE +
Tel.: +41 22 300 59 03 +
Fax: +41 22 300 59 09 +
E-mail: operation@beeone.ch

| Switzerland | *STMicroelectronics International NV* +
Succursale de Plan-les-Ouates +
Chemin du Champ-des-Filles 39 +
CH-1228 Plan-les-Ouates | *89 41 30* | Salvatore Acunto +
Chemin du Champ-des-Filles 39  +
CH-1228 Plan-les-Ouates +
Tel.: +41 78 744 7909 +
Fax: +41 22 929 2988 +
E-mail: salvatore.acunto@st.com

|===

==== Switzerland ADD

|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact h| Effective date of usage
| Switzerland | *Telecom26 AG*
Bahnhofstrasse 10 +
6300 ZUG | *89 41 31* | Michael Ashdown +
Bahnhofstrasse 10 +
6300 ZUG  +
Tel: +41 43 500 42 44 +
E-mail: mashdown@telecom26.ch | 1.III.2019

|===
