code: K.104
title:
  en: Method for identifying the transfer potential of the earth potential rise from
    high or medium voltage networks to the earthing system or neutral of low voltage
    networks
id: K.104
