code: X.667
title:
  en: 'Information technology - Procedures for the operation of object identifier
    registration authorities: Generation of universally unique identifiers and their
    use in object identifiers'
