code: Q.4001.1 v.1
title:
  en: 'IMS specific use of session initiation protocol and session description protocol;
    Conformance testing – Part 1: Protocol implementation conformance statement'
id: Q.4001.1 v.1
