code: Q.4004.1 v.1
title:
  en: 'Communication diversion using IP multimedia core network subsystem; Conformance
    testing – Part 1: Network side and user side; Protocol implementation conformance
    statement'
