code: Q.4009.2 v.1
title:
  en: 'Completion of communications to busy subscriber and completion of communications
    by no reply  using IP multimedia  core network  subsystem; Conformance test specification
    – Part 2: Test suite structure and test purposes'
id: Q.4009.2 v.1
