==== Mexico

===== Communication of 23.V.2019

_Granting of Recognized Operating Agency (ROA) status_

The _Instituto Federal de Telecomunicaciones (IFETEL)_, Ciudad de México, announces that the following telecommunication operators and service providers have been granted the status of Recognized Operating Agency (ROA), in accordance with Article 6 of, and Nos.1007 and 1008 of the Annex to, the Constitution of ITU.

The name of the telecommunication operators and service providers to which the status of Recognized Operating Agency (ROA) has been granted, is: _Mega Cable, S.A. de C.V._


===== Contact

Mr Ramón Olivares Chávez +
Mega Cable, S.A. de C.V. +
Av. Lázaro Cárdenas No. 1694, +
Col. Del Fresno, +
C.P. 44909, Guadalajara, +
Jalisco, +
México. +
Tel.: 52 (33) 3750 0020 Op.1 Ext: 61332 +
E-mail: rolivares@megacable.com.mx; juridicoregulatorio@megacable.com.mx

For further information, please contact:

Instituto Federal de Telecomunicaciones (IFETEL) +
Avenida Insurgentes Sur 1143 +
Col. Noche Buena +
03720 CIUDAD DE MÉXICO +
Mexico +
Tel: +52 (55) 5015 4208 +
E-mail: asuntosinternacionales@ift.org.mx +
URL: http://ucsweb.ift.org.mx/vrpc/

