code: Q.4008.2 v.1
title:
  en: 'Malicious communication identification using IP multimedia core network subsystem;
    Conformance test specification – Part 2: Test suite structure and test purposes;
    Network side'
id: Q.4008.2 v.1
