==== Moldova (Republic of) SUP

[width=100%]
|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact h| Date of cancellation
| Moldova (Republic of) | *I.M. Eventis Mobile s.r.l.* +
Str. Sadoveanu M.2 Off 5 mum. +
MD-2044 CHISINAU | *89 373 04* | Oleg Primak +
b.125 off.5, 31 August Str. +
CHISINAU MD-2012 +
Tel: +373 2223 4845 +
Fax: +373 2223 4851 +
E-mail: o.primak@eventismobile.md | 16.VIII.2013
|===

==== New Caledonia LIR

[width=100%]
|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact
| New Caledonia | *Office des Postes et des Télécommunications (OPT)* +
2 Rue Paul Monchovet +
Port Plaisance +
98841 NOUMEA CEDEX | *89 687 01* | Olivier Amat +
2, rue Monchovet +
98841 NOUMEA Cedex +
Tel: +687 268282 +
Fax: +687 289090 +
E-mail: olivier.amat@opt.nc
|===

==== Portugal LIR

[width=100%]
|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact
| Portugal | *Lycamobile Portugal, Lda* +
Rua José Carlos dos Santos, 14 +
1700-257 LISBOA | *89 351 04* | António Maria Spínola Brito Mendes Arnaut +
Rua José Carlos dos Santos, 14 +
1700-257 LISBOA +
Tel: +351 211 941 036 +
Fax: +
E-mail: antonio.arnaut@lycamobile.pt
|===

==== Singapore LIR

[width=100%]
|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact

| Singapore | *M1 Limited* +
10 International Business Park +
SINGAPORE 609928 | *89 65 03* | Matthias Foo +
10 International Business Park +
SINGAPORE 609928 +
Tel: +65 6655 1837 +
Fax: +65 6655 1977 +
E-mail: matthiasf@m1.com.sg

| Singapore | *StarHub Ltd* +
67 Ubi Avenue 1, +
#05-01 StarHub Green +
SINGAPORE 408942 | *89 65 05* | Sarah Tay +
67 Ubi Avenue 1, +
#05-01 StarHub Green +
SINGAPORE 408942 +
Tel: +65 6825 6504 +
Fax: +65 6821 7002 +
E-mail: saraht@starhub.com
|===

==== United Kingdom LIR

[width=100%]
|===
h| Country/geographical area h| Company Name/Address h| Issuer Identifier Number h| Contact

| United Kingdom | *Lycamobile UK Limited* +
3rd Floor Walbrook Building, +
195 Marsh Wall +
LONDON E14 9SG | *89 44 84* | Richard Hohenstein +
3rd Floor, Walbrook Building, +
195 Marsh Wall, +
LONDON E14 9SG +
Tel: +44 20 7536 6450 (ext 6585) +
Fax: +44 20 7536 6581 +
Email: richard.hohenstein@lycatel.com

| United Kingdom | *Lycatel Distribution UK Limited* +
3rd Floor Walbrook Building, +
195 Marsh Wall +
LONDON E14 9SG | *89 44 85* | Richard Hohenstein +
3rd Floor, Walbrook Building, +
195 Marsh Wall, +
LONDON E14 9SG +
Tel: +44 20 7536 6450 (ext 6585) +
Fax: +44 20 7536 6581 +
Email: richard.hohenstein@lycatel.com

|===


