==== Cuba (country code +53)

===== Communication of 13.II.2019

The _Ministerio de Comunicaciones_, La Habana, announces updates
to the national numbering plan of Cuba:

*Description of deletion of resource +
 for national E.164 numbering plan for country code 53:*

|===
h| +++<abbr title="national destination code">NDC</abbr>+++ +
or leading digits +
of +++<abbr title="national (significant) number">N(S)N</abbr>+++ h| Usage of ITU-T E.164 number h| Time and date of deletion

| 47 (NDC) | Geographical numbers for fixed telephony services - Area code for La Habana | Year 2013
|===

*Description of introduction of new resource +
 for national E.164 numbering plan for country code 53:*

|===
.2+h| +++<abbr title="national destination code">NDC</abbr>+++ +
or leading digits +
of +++<abbr title="national (significant) number">N(S)N</abbr>+++ 2+h| N(S)N number length .2+h| Usage of ITU-T E.164 number .2+h| Time and date of introduction
h| Minimum h| Maximum

| 47 (NDC) | 8 | 7 | Geographical numbers for fixed telephony services - Area code for the provinces of Mayabeque and Artemisa | Year 2013
|===


*Description of important numbers related to emergency services +
 and other services of social value:*

|===
5+h| Country: Cuba
h| Important Number h| Service h| Allocated or assigned h| E.164 number or national-only Number h| Note
| 107 | Maritime emergency | | single number |
|===

===== Contact

Eng. Wilfredo López Rodríguez +
 Director de Regulaciones
Ministerio de Comunicaciones
Plaza de la Revolución
Avenida Independencia No. 2 e/ 19 de mayo y Aranguren
10 600 CIUDAD DE LA HABANA
Cuba
Tel: +53 7 882 8135 +
 Fax: +53 7 883 5193 +
 E-mail: wilfredo.lopez@mincom.gob.cu

URL: www.mincom.gob.cu

==== Denmark (country code +45)

===== Communication of 8.II.2019

The _Danish Energy Agency_, Copenhagen, announces the following updates
to the national numbering plan of Denmark:

* Withdrawal – Carrier select code

|===
h| Provider h| Carrier select code h| Date of withdrawal
| Facilicom A/S | 1008 | 31.III.2019
|===

===== Communication of 13.II.2019

* Assignment – M2M communication

|===
h| Provider h| Numbering series h| Date of assignment
| Gigsky ApS | 37100140ijkl, 37100141ijkl, 37100142ijkl, 37100143ijkl, 37100144ijkl, 37100145ijkl, 37100146ijkl, 37100147ijkl, 37100148ijkl and 37100149ijkl | 12.II.2019
|===


===== Contact

Danish Energy Agency
Amaliegade 44
1256 COPENHAGEN K

Denmark +
 Tel: +45 33 92 67 00 +
 Fax: +45 33 11 47 43 +
 E-mail: ens@ens.dk +
 URL: www.ens.dk

==== French Polynesia (country code +689)

===== Communication of 8.II.2019

The _Direction générale de l'économie numérique (DGEN)_, Papeete,
announces the update to the general structure of the numbering plan
for French Polynesia following the arrival of VITI as new mobile operator in July 2018.
For information, VITI has announced that its mobiles services will be marketed
as of the second semester of 2019.

====== General structure of the numbering plan for French Polynesia

* Country code: +689
* Closed plan at eight (8) digits 
* Dialling format: AB PQ MC DU
* Destination: accessible interpersonal numbers

|===
h| Number blocks h| Usage of number h| Additional information
h| 4B PQ MC DU   h| Fixed telephone service h| Allocation
| 40 PQ MC DU | Geographical numbers | Office des postes et télécommunications (OPT)
| 49 PQ MC DU | Non-geographical numbers | Office des postes et télécommunications (OPT)
h| 8B PQ MC DU h| Mobile telephone service h| Allocation
| 87 PQ MC DU | Prepaid/postpaid mobile numbers | VINI
| 88 PQ MC DU | Prepaid/postpaid mobile numbers | VITI
| 89 PQ MC DU | Prepaid/postpaid mobile numbers | Pacific mobile Telecom / VODAFONE
|===


===== Contact

Direction générale de l'économie numérique (DGEN) +
Immeuble TORIKI +
rue Dumont d'Urville +
98714 Papeete +
TAHITI +
French Polynesia +
Tel: +689 40 54 48 60 +
E-mail: contact@dgen.gov.pf +
URL: www.service-public.pf/dgen/
