code: Q.3942.2
title:
  en: 'Conformance test specification for the terminating identification restriction
    using IP multimedia core network subsystem – Part 2: Network side; Test suite
    structure and test purposes'
