code: J.343.4
title:
  en: Hybrid-RR objective perceptual video quality measurement for HDTV and multimedia
    IP-based video services in the presence of a reduced reference signal and non-encrypted
    bitstream data
