GENERAL INFORMATION

== Lists annexed to the ITU Operational Bulletin

Note from TSB

A.	The following Lists have been published by TSB or BR as Annexes to the ITU Operational Bulletin (OB):

OB No.

* 1162	Mobile Network Codes (MNC) for the international identification plan for public networks and subscriptions (According to Recommendation ITU-T E.212 (09/2016)) (Position on 15 December 2018)

* 1161	List of Issuer Identifier Numbers for the International Telecommunication Charge Card (In accordance with Recommendation ITU-T E.118 (05/2006)) (Position on 1 December 2018)

* 1154	Status of Radiocommunications between Amateur Stations of Different Countries (In accordance with optional provision No. 25.1 of the Radio Regulations) and Form of Call Signs assigned by each Administration to its Amateur and Experimental Stations (Position on 15 August 2018)

* 1125	List of Signalling Area/Network Codes (SANC) (Complement to Recommendation ITU-T Q.708 (03/99)) (Position on 1 June 2017)

* 1125	List of terrestrial trunk radio mobile country codes (Complement to Recommendation ITU-T E.218 (05/2004)) (Position on 1 June 2017)

* 1117	List of mobile country or geographical area codes (Complement to Recommendation ITU T E.212 (09/2016)) (Position on 1 February 2017).

* 1114	List of Recommendation ITU-T E.164 assigned country codes (Complement to Recommendation ITU T E.164 (11/2010)) (Position on 15 December 2016)

* 1109	List of International Signalling Point Codes (ISPC) (According to Recommendation ITU-T Q.708 (03/99)) (Position on 1 October 2016)

* 1096	Legal time 2016

* 1060	List of ITU Carrier Codes (According to ITU-T Recommendation M.1400 (03/2013) (Position on 15 September 2014)

* 1015	Access codes/numbers for mobile networks (According to ITU-T Recommendation E.164 (11/2010)) (Position on 1 November 2012)

* 1002	List of Country or Geographical Area Codes for non-standard facilities in telematic services (Complement to ITU-T Recommendation T.35 (02/2000)) (Position on 15 April 2012)

* 1001	List of the national authorities designated to assign ITU-T Recommendation T.35 terminal provider codes (Position on 1 April 2012)

* 1000	Service Restrictions (Recapitulatory list of service restrictions in force relating to telecommunications operation) (Position on 15 March 2012)

* 994	Dialling Procedures (International prefix, national (trunk) prefix and national (significant) number) (In accordance with ITU-T Recommendation E.164 (11/2010)) (Position on 15 December 2011)

* 991	Call-Back and alternative calling procedures (Res. 21.PP-2006)

* 980	List of Telegram Destination Indicators (In accordance with ITU-T Recommen¬dation F.32 (10/1995)) (Position on 15 May 2011)

* 978	List of Telex Destination Codes (TDC) and Telex Network Identification Codes (TNIC) (Complement to ITU T Recommendations F.69 (06/1994) and F.68 (11/1988)) (Position on 15 April 2011)

* 977	List of Data Network Identification Codes (DNIC) (According to ITU-T Recommendation X.121 (10/2000)) (Position on 1 April 2011)

* 976	List of Data Country or Geographical Area Codes (Complement to ITU T Recommen¬dation X.121 (10/2000)) (Position on 15 March 2011)

* 974	List of Names of Administration Management Domains (ADMD) (In accordance with ITU T F.400 and X.400 series Recommendations) (Position on 15 February 2011)

* 955	Various tones used in national networks (According to ITU-T Recommendation E.180 (03/98)) (Position on 1 May 2010)

* 669	Five-letter Code Groups for the use of the International Public Telegram Service (According to ITU-T Recommendation F.1 (03/1998))


B.	The following Lists are available online from the ITU-T website:

* List of ITU Carrier Codes (ITU-T Rec. M.1400 (03/2013))	www.itu.int/ITU-T/inr/icc/index.html
* Bureaufax Table (ITU-T Rec. F.170)	www.itu.int/ITU-T/inr/bureaufax/index.html
* List of recognized operating agencies (ROAs)	www.itu.int/ITU-T/inr/roa/index.html
