code: Q.3403 v.1
title:
  en: 'IP multimedia call control protocol based on the session initiation protocol
    and the session description protocol - Basic call: Requirements for the user side
    and the network side'
id: Q.3403 v.1
