code: J.343.3
title:
  en: Hybrid-RRe objective perceptual video quality measurement for HDTV and multimedia
    IP-based video services in the presence of a reduced reference signal and encrypted
    bitstream data
