code: P.1203.2
title:
  en: Parametric bitstream-based quality assessment of progressive download and adaptive
    audiovisual streaming services over reliable transport – Audio quality estimation
    module
id: P.1203.2
