code: H.850.2
title:
  en: 'Conformance of ITU-T H.810 personal health system: Personal Health Devices
    interface Part 10B: Transcoding for Bluetooth Low Energy: Personal Health Gateway
    – Blood pressure'
id: H.850.2
