code: Q.3229
title:
  en: Signalling requirements and protocol at the M2 interface between the transport
    location management physical entity and the handover decision and control physical
    entity
id: Q.3229
