code: Q.4012.3 v.1
title:
  en: 'Anonymous communication rejection and communication barring using IP multimedia
    core network subsystem; Conformance test specification – Part 3: Test suite structure
    and test purposes; User side'
