code: Q.4015.2 v.1
title:
  en: 'Interworking between the IP multimedia core network subsystem and circuit switched
    networks; Conformance testing – Part 2: Test suite structure and test purposes'
id: Q.4015.2 v.1
