==== Armenia (country code +374)

===== Communication of 11.IV.2019

The _Ministry of Transport, Communication and Information Technologies_, Yerevan,
announces the updated version of National Numbering Plan of Armenia.

[cols="8*"]
|===
.2+h| Marz name (Province)
.2+h| Destination name
6+h| Existing N(S)N
h| NDC
h| Additional digits
4+h| Inter-regional destination code + SN
4+h| 
4+h| Geographic numbers for fixed telephony services
4+h| 
h| VEON Armenia (Beeline)
h| UCOM
h| GNC-Alfa (Rostelecom)
h| Crossnet


.4+h| Yerevan .4+| Telephone exchanges
| 10 | - | 2xxxxx, 3xxxxx, 4xxxxx, 5xxxxx, 6xxxxx, 7xxxxx, 8xxxxx, 9xxxxx | | |
| 11 | - | | 2xxxxx, 3xxxxx, 4xxxxx, 5xxxxx, 6xxxxx, 7xxxxx, 8xxxxx, 9xxxxx | |
| 12 | - | | | 2xxxxx, 3xxxxx, 4xxxxx, 5xxxxx, 6xxxxx, 7xxxxx, 8xxxxx, 9xxxxx |
| 15 | - | | | | 2xxxxx, 3xxxxx, 4xxxxx, 5xxxxx, 6xxxxx, 7xxxxx, 8xxxxx, 9xxxxx


.13+h| Kotayk

h| Abovyan .5+| 222 .5+| - | 2xxxx, 3xxxx, 4xxxx, 7xxxx, 9xxxx .4+| 5xxxx .4+| 81xxx .13+|
| Arzni | 94xxx
| Arinj | 98xxx
| Geghashen | 97xxx
| Abovyan CDMA | 6xxxx | |

h| Hrazdan .3+| 223 .3+| - | 2xxxx, 3xxxx, 4xxxx, 9xxxx | 70xxx, 71xxx, 72xxx, 73xxx, 74xxx | 810xx, 811xx, 812xx, 813xx, 814xx
| Tsaghkadzor | 5xxxx | 75xxx, 76xxx, 77xxx, 78xxx, 79xxx | 815xx, 816xx, 817xx, 818xx, 819xx
| Hrazdan CDMA | 6xxxx | |

h| Charentsavan .2+| 226 .2+| - | 2xxxx, 4xxxx, 7xxxx | 3xxxx | 81xxx
| Charentsavan CDMA | 6xxxx | |

h| Eghvard .3+| 224 .3+| - | 2xxxx, 3xxxx, 5xxxx, 9xxxx .2+| 2xxxx, 3xxxx, 5xxxx, 9xxxx | 810xx, 811xx, 812xx, 813xx, 814xx
h| Nor-Hachn | 4xxxx | 815xx, 816xx, 817xx, 818xx, 819xx
| Eghvard CDMA | 6xxxx | |


.14+h| Armavir

h| Echmiadzin .3+| 231 .3+| - | 4xxxx, 5xxxx, 9xxxx | 2xxxx | 810xx, 811xx, 812xx, 813xx, 814xx, 815xx, 816xx .14+|
| Zvartnots | 7xxxx | 3xxxx | 817xx, 818xx, 819xx
| Echmiadzin CDMA | 6xxxx | |

h| Armavir .8+| 237 .8+| - | 2xxxx, 5xxxx, 7xxxx, 9xxxx | 40xxx, 41xxx, 42xxx, 43xxx, 44xxx, 45xxx, 46xxx | 810xx, 811xx, 812xx, 813xx, 814xx, 815xx, 816xx
| Metsamor | 3xxxx .6+| 40xxx, 41xxx, 42xxx, 43xxx, 44xxx, 45xxx, 46xxx .6+| 810xx, 811xx, 812xx, 813xx, 814xx, 815xx, 816xx
| v. Armavir | 71xxx
| Bambakashat | 79xxx
| Mrgashat | 72xxx
| Nalbandyan | 92xxx
| Tandzyt | 96xxx
| Armavir CDMA | 6xxxx | |

h| Baghramian .3+| 233 .3+| - | 2xxxx, 7xxxx, 9xxxx .2+| 3xxxx .2+| 81xxx
| Myasnikian | 74xxx
| Baghramian CDMA | 6xxxx | |


.10+h| Ararat

h| Vedi .5+| 234 .5+| - .2+| 2xxxx, 3xxxx, 4xxxx, 8xxxx, 9xxxx | 70xxx, 71xxx, 72xxx, 73xxx, 74xxx | 510xx, 511xx, 512xx, 513xx, 514xx .10+|
h| Ararat .2+| 75xxx, 76xxx, 77xxx, 78xxx, 79xxx .2+| 515xx, 516xx, 517xx, 518xx, 519xx
| Urtsadzor | 86xxx
| Vedi CDMA  .2+| 6xxxx .2+| .2+|
| Ararat CDMA

h| Artashat .3+| 235 .3+| - | 2xxxx, 5xxxx, 7xxxx, 9xxxx .2+| 3xxxx .2+| 81xxx
| Norashen | 92xxx, 93xxx
| Artashat CDMA | 6xxxx | |

h| Masis .2+| 236 .2+| - | 2xxxx, 3xxxx, 4xxxx, 9xxxx | 5xxxx | 81xxx
| Masis CDMA | 6xxxx | |


.16+h| Aragatsotn

h| Ashtarak .4+| 232 .4+| - | 2xxxx, 3xxxx, 9xxxx .3+| 4xxxx .3+| 81xxx .16+|
| Byurakan | 94xxx
| Ohanavan | 90xxx
| Ashtarak CDMA | 6xxxx | |

h| Talin .5+| 249 .5+| - | 2xxxx, 3xxxx, 7xxxx, 9xxxx .4+| 4xxxx .4+| 81xxx
| Aragats | 95xxx
| Katnaghbyur | 73xxx
| Mastara | 97xxx
| Talin CDMA | 6xxxx | |

h| Aparan .4+| 252 .4+| - | 2xxxx, 3xxxx, 9xxxx .3+| 4xxxx .3+| 81xxx
| Artavan | 95xxx
| Quchak | 91xxx
| Aparan CDMA | 6xxxx | |

h| Tsaghkahovit .3+| 257 | 0 | 2xxx | |
| Tsaghkahovit region .2+| - | 2xxxx | 3xxxx | 81xxx
| Tsaghkahovit CDMA | 6xxxx | |


.14+h| Shirak

h| Gyumri .3+| 312 .3+| - | 2xxxx, 3xxxx, 4xxxx, 5xxxx | 9xxxx | 850xx, 851xx, 852xx, 853xx, 854xx, 855xx, 856xx, 857xx, 858xx .14+|
h| Akhurian region | 7xxxx | 80xxx, 81xxx, 82xxx, 83xxx, 84xxx | 859xx
h| Gyumri CDMA | 6xxxx | |
h| Ashotsk region .2+| 245 .2+| - | 2xxxx, 3xxxx | 4xxxx | 81xxx
| Ashotsk CDMA | 6xxxx | |

h| Amasia region .2+| 246 .2+| - | 2xxxx, 3xxxx | 4xxxx | 81xxx
| Amasia CDMA | 6xxxx | |

h| Maralik .3+| 242 .3+| - | 2xxxx, 3xxxx, 4xxxx, 9xxxx .2+| 5xxxx .2+| 81xxx
| Sarnaghbyur | 31xxx
| Maralik CDMA | 6xxxx | |

h| Artik .3+| 244 .3+| - | 2xxxx, 3xxxx, 5xxxx, 9xxxx .2+| 4xxxx .2+| 81xxx
| Panik | 92xxx
| Artik CDMA | 6xxxx | |

| Arapi | 243 | 00 | 5xx, 6xx | |


.13+h| Lori

h| Vanadzor .2+| 322 .2+| - | 2xxxx, 3xxxx, 4xxxx, 5xxxx, 60xxx, 61xxx, 62xxx, 63xxx, 64xxx, 65xxx, 66xxx, 9xxxx | 7xxxx | 81xxx .13+|
| Vanadzor CDMA | 6xxxx | |

h| Spitak region .2+| 255 .2+| - | 2xxxx, 3xxxx | 4xxxx | 81xxx
| Spitak CDMA | 6xxxx | |

h| Alaverdi .4+| 253 .4+| - | 2xxxx, 3xxxx, 4xxxx, 5xxxx .3+| 7xxxx .3+| 81xxx
| Akhtala | 52xxx
| Tumanyan | 57xxx
| Alaverdi CDMA | 6xxxx | |

h| Tashir .3+| 254 .3+| - | 2xxxx, 7xxxx, 9xxxx .2+| 3xxxx .2+| 81xxx
| Metsavan | 94xxx
| Tashir CDMA | 6xxxx | |

h| Stepanavan .2+| 256 .2+| - | 2xxxx, 3xxxx, 9xxxx | 4xxxx | 81xxx
| Stepanavan CDMA | 6xxxx | |


.12+h| Gegharkunik 

h| Sevan .2+| 261 .2+| - | 2xxxx, 3xxxx, 9xxxx | 4xxxx | 4xxxx .12+|
| Sevan CDMA | 6xxxx | |

h| Martuni .3+| 262 .3+| - | 2xxxx, 4xxxx, 5xxxx, 7xxxx, 9xxxx .2+| 3xxxx .2+| 3xxxx
| Vardenik | 52xxx, 53xxx
| Martuni CDMA | 6xxxx | |

h| Gavar .2+| 264 .2+| - | 2xxxx, 3xxxx, 4xxxx, 9xxxx | 5xxxx | 81xxx
| Gavar CDMA | 6xxxx | |

h| Vardenis .2+| 269 .2+| - | 2xxxx, 3xxxx, 7xxxx, 9xxxx | 4xxxx | 81xxx
| Vardenis CDMA | 6xxxx | |

h| Chambarak .3+| 265 .3+| - | 2xxxx, 3xxxx, 9xxxx .2+| 4xxxx .2+| 81xxx
| Vahan | 96xxx
| Chambarak CDMA | 6xxxx | |


.19+h| Tavush

h| Ijevan .4+| 263 .4+| - | 3xxxx, 4xxxx, 7xxxx, 9xxxx .3+| 2xxxx .3+| 81xxx .19+|
| Aygehovit | 74xxx
| Achajur | 92xxx
| Ijevan CDMA | 6xxxx | |

h| Berd .5+| 267 .5+| - | 2xxxx, 5xxxx, 7xxxx, 9xxxx .4+| 3xxxx .4+| 81xxx
| Mosesgegh | 96xxx
| Navur | 91xxx
| Norashen | 97xxx
| Berd CDMA | 6xxxx | |

h| Noyemberian .5+| 266 .5+| - | 2xxxx, 5xxxx, 7xxxx, 9xxxx .4+| 3xxxx .4+| 81xxx
| Voskepar | 96xxx
| Koti | 99xxx
| Koghb | 52xxx, 53xxx
| Noyemberian CDMA | 6xxxx | |

h| Dilijan .5+| 268 | - |2xxxx, 3xxxx, 9xxxx .3+| 4xxxx .3+| 81xxx
| Haghartsin | | 95xxx
| Teghut | | 97xxx
| Dilijan (4 digits) | 0 | xxxx | |
| Dilijan CDMA | - | 6xxxx | |


.10+h| Vayots dzor

h| Yeghegnadzor .4+| 281 .4+| - | 2xxxx, 5xxxx, 9xxxx .3+| 3xxxx .3+| 81xxx .10+|
| Malishka | 95xxx
| Shatin | 99xxx
| Yeghegnadzor CDMA | 6xxxx | |

h| Vaik .3+| 282 .3+| - | 2xxxx, 928xx, 929xx .2+| 3xxxx .2+| 81xxx
| Vaik region | 9xxxx
| Vaik CDMA | 6xxxx | |

h| Jermuk .3+| 287 .3+| - | 2xxxx, 9xxxx .2+| 3xxxx .2+| 81xxx
| Gndevaz | 94xxx
| Jermuk CDMA | 6xxxx | |


.12+h| Syunik

h| Sisian region .3+| 283 | - | 2xxxx, 7xxxx, 8xxxx, 9xxxx | 3xxxx | 51xxx .12+|
| Sisian (4 digits) | 0 | xxxx | |
| Sisian CDMA | - | 6xxxx | |

h| Goris region .2+| 284 .2+| - | 2xxxx, 3xxxx, 4xxxx, 9xxxx | 5xxxx | 81xxx
| Goris CDMA | 6xxxx | |

h| Kapan .3+| 285 .3+| - | 2xxxx, 5xxxx, 9xxxx | 40xxx, 41xxx, 42xxx, 43xxx, 44xxx | 810xx, 811xx, 812xx, 813xx, 814xx
| Kajaran | 3xxxx | 45xxx, 46xxx, 47xxx, 48xxx, 49xxx | 815xx, 816xx, 817xx, 818xx, 819xx
| Kapan CDMA | 6xxxx | |

h| Meghri .4+| 286 .4+| - | 4xxxx, 9xxxx | 3xxxx | 810xx, 811xx, 812xx, 813xx, 814xx
| Agarak | 2xxxx .2+| 5xxxx .2+| 815xx, 816xx, 817xx, 818xx, 819xx
| Shvanidzor | 95xxx
| Meghri CDMA | 6xxxx | |


|===


[cols="4*"]
|===
.2+| .2+| 2+h| Existing N(S)N
h| NDC h| SN

.3+h| Non-geographic number for mobile services

h| VEON Armenia GSM  (Beeline) | 91, 96, 99, 43, 33 | xxxxxx
h| MTS Armenia GSM  (Vivacell MTS) | 77, 88, 93, 94, 98 | xxxxxx
h| Ucom GSM (Ucom) | 41, 44, 55, 95 | xxxxxx
|===


[cols="5*"]
|===
| | 3+h| Existing N(S)N
| | h| NDC h| Additional digits h| SN

.14+h| Non-geographical code for fixed telephony services

h| Internet Communications (Arminco) .14+| 60 .14+| - | 27xxxx, 62xxxx, 66xxxx
h| Dzoraghbyur Hamalir | 28xxxx
h| Hi-Tech Gateway | 351xxx
h| Web | 36xxxx
h| CrossNet | 37xxxx, 40xxxx, 43xxxx, 47xxxx, 48xxxx, 49xxxx
h| Netsys | 39xxxx, 63xxxx
h| Ucom | 38xxxx, 42xxxx, 44xxxx, 50xxxx, 51xxxx, 52xxxx, 53xxxx, 54xxxx, 65xxxx
h| Griar Telecom | 45xxxx, 56xxxx, 57xxxx, 58xxxx, 59xxxx, 60xxxx
h| GNC-Alfa | 46xxxx, 71xxxx, 72xxxx, 73xxxx, 74xxxx, 75xxxx
h| Ayter | 64xxxx
h| MTS Armenia | 61xxxx, 67xxxx, 68xxxx, 69xxxx, 70xxxx, 77/0000-1200,3300-3400,6600-6700, 7000-9200/, 78/0000-0800,7700-8900/, 80/0000-0100,0800-2400,7770-8990,9900-9999/, 81/0000-1200,8800-8999/
h| HNet | 82xxxx
h| VEON Armenia | 83xxxx, 84xxxx, 85xxxx
h| Arpinet | 86xxxx, 87xxxx, 88xxxx, 89xxxx, 90xxxx

|===

===== Contact

Ministry of Transport, Communication and Information Technologies +
 3/3 Vazgen Sargsyan Street +
0010 YEREVAN +
 Armenia +
 Tel: +374 10590009 +
 Fax: +374 10523862 +
 E-mail: mailto:info@mtcit.am[info@mtcit.am] +
 URL: www.mtcit.am


==== Burkina Faso (country code +226)

===== Communication of 12.IV.2019

The _Autorité de Régulation des Communications Electroniques et des Postes (ARCEP)_, Ouagadougou,
announces the following updates to the national numbering plan Burkina Faso.

Assignment of new prefix AB=01:

|===
.2+h| +++<abbr title="national destination code">NDC</abbr>+++ +
or leading digits +
of +++<abbr title="national (significant) number">N(S)N</abbr>+++ 2+h| N(S)N number length .2+h| Usage of ITU-T E.164 number .2+h| Time and date of introduction
h| Minimum h| Maximum

| 01 | 8 | 8 | Non-geographic number - Mobile telephone service a| ONATEL-SA Burkina Faso | 2019-04-15-00:00 (UTC)
|===

===== Contact

Autorité de Régulation des Communications Electroniques et des Postes (ARCEP) +
B.P. 6437 +
 OUAGADOUGOU 01 +
 Burkina Faso +
 Tel: +226 25 37 53 60/61/62 +
 Fax: +226 25 37 53 64 +
 E-mail: secretariat@arcep.bf +
 URL: www.arcep.bf


==== Denmark (country code +45)

===== Communication of 12.IV.2019

The _Danish Energy Agency_, Copenhagen, announces the following updates
to the national numbering plan of Denmark:

* Withdrawal – Mobile communication services
+
|===
h| Provider h| Numbering series h| Date of withdrawal
| Plenti ApS | 4940efgh | 31.XII.2018
|===

* Assignment – Mobile communication services
+
|===
h| Provider h| Numbering series h| Date of assignment
| TDC A/S | 4940efgh | 1.I.2019
| Telenor Connexion AB | 345defgh and 346defgh | 8.IV.2019
| Supertel A/S | 7871efgh | 1.V.2019

|===

* Assignment – Fixed communication services
+
|===
h| Provider h| Numbering series h| Date of assignment
| Viptel ApS | 70405fgh and 54404fgh | 8.IV.2019
|===


===== Contact

Danish Energy Agency

Amaliegade 44

1256 COPENHAGEN K

Denmark +
 Tel: +45 33 92 67 00 +
 Fax: +45 33 11 47 43 +
 E-mail: ens@ens.dk +
 URL: www.ens.dk


==== Myanmar (country code +95)

===== Communication of 12.IV.2019

The _Ministry of Transport and Communications_, Nay Pyi Taw, announces that the following
updated numbering scheme has been added to the national numbering plan of Myanmar:

_Description of introduction of new resources for +
 national E.164 numbering plan for country code + 95:_

*AUTO EXCHANGE NUMBERING (Geographic)*

[cols="9*"]
|===
.2+h| Sr No. .2+h| Area Code 2+h| Subscriber Number .2+h| Area .2+h| Type of Exchange .2+h| Digit Length (including area code) .2+h| Licensee .2+h| Remark
h| Exchange Code h| Station Number

| 1 | 1 | 23 | 99 000 - 99 999 | Yangon (Blue Ocean Call Center)
| PABX | 8 | Myanma Post and Telecommunication |
| 2 | 1 | 33 | 30 000 - 39 999 | Yangon (MPT Satellite) |
| 8 | Myanma Post and Telecommunication |
| 3 | 58 | 51 | 000 - 999 | MYAWADDY | DMS-10 | 7 | Myanma Post and Telecommunication |
| 4 | 63 | 20 | 28 000 - 28 999 | MAGWAY | ZTE SS | 9 | Myanma Post and Telecommunication |
| 5 | 85 | 51 | 78 000 - 78 999 | YADANAPON TELEPORT | HUAWEI SS | 9 | Myanma Post and Telecommunication |
| 6 | 56 | 20 | 20 000 - 23 999 | MANDALAY | ZTE (IP) | 9 | Myanma Post and Telecommunication |
| 7 | 81 | 41 | 0 000 - 0 999 | NAUNGTAYAR | KY 1000 XM | 8 | Myanma Post and Telecommunication | Replace 41 xxx with 410 xxx
| 8 | 83 | 2070 | 000 - 999 | HPASAUNG/MESE | KY-1000 | 8 | Myanma Post and Telecommunication | Add AREA NAME MESE

|===


*Mobile Numbering*

|===
h| Sr No. h| Area Code h| Number series h| System h| Digit Length (including area code) h| Operator
| 1 | 9 | 67x xxx - xxx | WCDMA / GSM | 10 | Telecom International Myanmar Co., Ltd
|===

===== Contact

Ministry of Transport and Communications +
Posts and Telecommunications Department (PTD) +
Building No. 2, +
NAY PYI TAW +
Myanmar +
Tel: +95 67 407 225 +
Fax: +95 67 407 216 +
E-mail: dg.ptd@mptmail.net.mm
