code: Q.3231
title:
  en: Signalling requirements and protocol at the Ne interface between the transport
    location management physical entity and the network access configuration physical
    entity
id: Q.3231
