code: Q.3941.4
title:
  en: 'Network integration testing between SIP and ISDN/PSTN network signalling protocols
    – Part 4: Abstract test suite and partial protocol implementation extra information
    for testing proforma specification for SIP-SIP'
id: Q.3941.4
