code: H.850.3
title:
  en: 'Conformance of ITU-T H.810 personal health system: Personal Health Devices
    interface Part 10C: Transcoding for Bluetooth Low Energy: Personal Health Gateway
    - Heart-rate'
