code: Q.4003.1 v.1
title:
  en: 'Communication HOLD using IP multimedia core network subsystem; Conformance
    Testing – Part 1: Network side and user side; Protocol implementation conformance
    statement'
