code: Q.3942.3
title:
  en: 'Conformance test specification for the terminating identification restriction
    using IP multimedia core network subsystem – Part 3: User side; Test suite structure
    and test purposes'
id: Q.3942.3
