code: Q.3232
title:
  en: Signalling requirements and protocol at the Nc interface between the transport
    location management physical entity and the transport authentication and authorization
    physical entity
