code: Q.3943.3
title:
  en: 'Conformance tests specification for the originating identification presentation
    and originating identification restriction using the IP multimedia core network
    subsystem – Part 3: User side – Test suite structure and test purposes'
