code: Q.4008.3 v.1
title:
  en: 'Malicious communication identification using IP multimedia core network subsystem;
    Conformance test specification – Part 3: Test suite structure and test purposes;
    User side'
id: Q.4008.3 v.1
