==== Section VI

===== ADD

DP12::
Airbus Defence and Space GmbH, Willy-Messerschmitt-Strasse 1, 82024, Taufkirchen.
E-Mail: mailto:stefan.gramolla@airbus.com[stefan.gramolla@airbus.com], Tel: +49 89 31 79 51 82,
Fax: +49 89 31 79 64 50, URL: http://www.airbus.com/[www.airbus.com],
Contact person: Stefan Gramolla.

DP15::
GESAT GmbH, Hanauer Landstrasse 121a, 60314, Frankfurt Germany.
E-Mail: mailto:einetter@gestat.com[einetter@gestat.com], Tel: +49 69 96 21 80 13,
Fax: +49 69 96 21 80 99, URL: http://www.gesat.com/[www.gesat.com],
Contact person: Hubert Einetter

GR12::
RADIOHELLENIC MANAGEMENT AND EXPLOITATION COMPAGNY Single
Member P.C Posidonos 26, GR 175 61 P Faliro, Athens, Greece.

===== REP

DP04::
DH-INTERCOM GmbH & Co. KG, Lauenburger Landstrasse 11,
21039 Boernsen, Germany.
E-Mail: mailto:info.de@speedcast.com[info.de@speedcast.com], Tel: +49 40 53 797-8290,
URL: http://www.dh-intercom.de/[www.dh-intercom.de],
Contact Person: Stefan Alberts.

DP05::
DH-INTERCOM GmbH & Co. KG, Lauenburger Landstrasse 11,
21039 Boernsen, Germany.
E-Mail: mailto:info.de@speedcast.com[info.de@speedcast.com], Tel: +49 40 53 797-8290,
URL: http://www.dh-intercom.de/[www.dh-intercom.de],
Contact Person: Stefan Alberts.

DP16::
Pro Nautas B.V. GmbH, Hafenstrasse 2a, 26789 Leer, Germany.
E-Mail: mailto:SListewnik@pro-nautas.de[SListewnik@pro-nautas.de], Tel: +49 17 49 09 91 99,
URL: http://www.pro-nautas.com/[www.pro-nautas.com],
Contact Person: Stephan Listewnik.

===== SUP

DP09::
MoBillan GmbH, P.O. Box 31 01 23, D-53201 Bonn, Germany.
E-Mail: mailto:info@mobillan.com[info@mobillan.com], Tel: +49 228 422690,
Fax: +49 228 4226916, URL: http://www.mobillan.com/[www.mobillan.com].

DP10::
Satellution Gesellschaft für Satellitenkommunikation mbH, Heinrich-Böcking Str. 7,
D-66121 Saarbrücken, Germany.
