code: Q.3325
title:
  en: 'Resource control protocol No. 5 (rcp5) – Protocol at the interface between
    transport resource control physical entity and policy decision physical entity
    (Rt interface): Diameter-based'
