==== Section VI

===== SUP

US04::
Seven Seas Communications Inc., 1700 East Las Olas Blvd., Suite 202,
Ft. Lauderdale, FL 33301, United States.
Contact Person: Gary A. Cantor.

US05::
Omnet, Inc., P.O. Box 1285, 21 North Central Avenue Staunton, VA 24402,
United States.
Contact Person: Susan Kubany, President.

US06::
KFS Worl Communications dba GLOBE WIRELESS,
1571 Robert J. Conlan Blvd., Palm Bay, FL 32905, United States.
Contact Person: Barbara A. Curran, Invoicing Specialist, Tel: +1 321 309 1392,
E-mail: barbara.curran@globewireless.com.

US08::
ShipCom, L.L.C. (formely M M R Radio, L.L.C.), 7700 Rinla Ave., Mobile,
AL 36619-1199, United States.
Contact Persons: Rene Stiegler, President,
Tel: +1 251 666 5110, Paula Ramage, Assistant, E-mail: pramage@wlo.com.

US10::
Exxon Communications Company, P.O. Box 4934, Houston, TX 77210-4934,
United States.
Contact Person: Mary Carol Wichel, Licensing Administrator, Fax: +1 713 431 7310.

US12::
Raytheon Service Co., 1348 Hainesport Road, Mt. Laurel, NJ 08054,
United States.
Contact Person: Charles D. Parker.
